on: [push, pull_request]

jobs:
  test:
    strategy:
    runs-on: ${{ matrix.os }}
    matrix:
      os: [ubuntu-latest, macos-latest]
      java-version: ['11', '14']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
      - run: ./gradlew check

